using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class ModuleDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<Compilation> compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(compilationProvider, (spc, compilation) =>
        {
            INamedTypeSymbol? moduleInterface = compilation.GetTypeByMetadataName("Core.IModule");
            if (moduleInterface == null) return;

            var moduleNames = new List<string>();
            
            // This includes the Main project and all referenced Modules (Auth, Sales, etc.)
            var allAssemblies = compilation.SourceModule.ReferencedAssemblySymbols
                .Concat(new[] { compilation.Assembly });

            foreach (var assembly in allAssemblies)
            {
                var modulesInAssembly = FindIModuleImplementations(assembly.GlobalNamespace, moduleInterface);
                moduleNames.AddRange(modulesInAssembly);
            }

            GenerateSource(spc, moduleNames.Distinct());
        });
    }

    private IEnumerable<string> FindIModuleImplementations(INamespaceSymbol ns, INamedTypeSymbol interfaceSymbol)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol childNs)
            {
                foreach (var found in FindIModuleImplementations(childNs, interfaceSymbol))
                    yield return found;
            }
            else if (member is INamedTypeSymbol type && 
                     !type.IsAbstract && 
                     type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol)))
            {
                yield return type.ToDisplayString();
            }
        }
    }

    private void GenerateSource(SourceProductionContext context, IEnumerable<string> modules)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Core;");
        sb.AppendLine("public static class GeneratedModuleDiscovery {");
        sb.AppendLine("    public static List<IModule> GetModules() {");
        sb.AppendLine("        return new List<IModule> {");
        foreach (var name in modules) sb.AppendLine($"            new {name}(),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource("GeneratedModuleDiscovery.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}